# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_tool.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(913, 694)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAutoFillBackground(False)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.te_Recv = QtWidgets.QTextEdit(Form)
        self.te_Recv.setObjectName("te_Recv")
        self.gridLayout.addWidget(self.te_Recv, 0, 0, 1, 11)
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 6, 0, 1, 1)
        self.cob_DataBits = QtWidgets.QComboBox(self.frame)
        self.cob_DataBits.setObjectName("cob_DataBits")
        self.cob_DataBits.addItem("")
        self.cob_DataBits.addItem("")
        self.cob_DataBits.addItem("")
        self.cob_DataBits.addItem("")
        self.gridLayout_4.addWidget(self.cob_DataBits, 1, 1, 1, 1)
        self.cob_Baudrate = QtWidgets.QComboBox(self.frame)
        self.cob_Baudrate.setObjectName("cob_Baudrate")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.cob_Baudrate.addItem("")
        self.gridLayout_4.addWidget(self.cob_Baudrate, 0, 1, 1, 1)
        self.cob_StopBits = QtWidgets.QComboBox(self.frame)
        self.cob_StopBits.setObjectName("cob_StopBits")
        self.cob_StopBits.addItem("")
        self.cob_StopBits.addItem("")
        self.cob_StopBits.addItem("")
        self.gridLayout_4.addWidget(self.cob_StopBits, 4, 1, 1, 1)
        self.cob_Parity = QtWidgets.QComboBox(self.frame)
        self.cob_Parity.setObjectName("cob_Parity")
        self.cob_Parity.addItem("")
        self.cob_Parity.addItem("")
        self.cob_Parity.addItem("")
        self.cob_Parity.addItem("")
        self.cob_Parity.addItem("")
        self.gridLayout_4.addWidget(self.cob_Parity, 6, 1, 1, 1)
        self.cob_FlowCtrl = QtWidgets.QComboBox(self.frame)
        self.cob_FlowCtrl.setObjectName("cob_FlowCtrl")
        self.cob_FlowCtrl.addItem("")
        self.cob_FlowCtrl.addItem("")
        self.cob_FlowCtrl.addItem("")
        self.cob_FlowCtrl.addItem("")
        self.gridLayout_4.addWidget(self.cob_FlowCtrl, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.chk_HexSend = QtWidgets.QCheckBox(Form)
        self.chk_HexSend.setObjectName("chk_HexSend")
        self.gridLayout.addWidget(self.chk_HexSend, 1, 10, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.pb_Send = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_Send.sizePolicy().hasHeightForWidth())
        self.pb_Send.setSizePolicy(sizePolicy)
        self.pb_Send.setObjectName("pb_Send")
        self.gridLayout.addWidget(self.pb_Send, 2, 10, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 7, 1, 3)
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_8.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_8.setSpacing(1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 1, 1, 1, 1)
        self.lbl_Com = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Com.sizePolicy().hasHeightForWidth())
        self.lbl_Com.setSizePolicy(sizePolicy)
        self.lbl_Com.setObjectName("lbl_Com")
        self.gridLayout_7.addWidget(self.lbl_Com, 1, 0, 1, 1)
        self.cob_Com = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cob_Com.sizePolicy().hasHeightForWidth())
        self.cob_Com.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cob_Com.setFont(font)
        self.cob_Com.setObjectName("cob_Com")
        self.gridLayout_7.addWidget(self.cob_Com, 1, 2, 1, 1)
        self.pb_OpenOrClose = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_OpenOrClose.sizePolicy().hasHeightForWidth())
        self.pb_OpenOrClose.setSizePolicy(sizePolicy)
        self.pb_OpenOrClose.setObjectName("pb_OpenOrClose")
        self.gridLayout_7.addWidget(self.pb_OpenOrClose, 1, 3, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 2)
        self.te_Send = QtWidgets.QTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_Send.sizePolicy().hasHeightForWidth())
        self.te_Send.setSizePolicy(sizePolicy)
        self.te_Send.setObjectName("te_Send")
        self.gridLayout.addWidget(self.te_Send, 2, 1, 2, 9)
        self.chk_HexRecv = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_HexRecv.sizePolicy().hasHeightForWidth())
        self.chk_HexRecv.setSizePolicy(sizePolicy)
        self.chk_HexRecv.setObjectName("chk_HexRecv")
        self.gridLayout.addWidget(self.chk_HexRecv, 1, 2, 1, 1)
        self.pb_ClearRecv = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_ClearRecv.sizePolicy().hasHeightForWidth())
        self.pb_ClearRecv.setSizePolicy(sizePolicy)
        self.pb_ClearRecv.setObjectName("pb_ClearRecv")
        self.gridLayout.addWidget(self.pb_ClearRecv, 1, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_10.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_10.setSpacing(1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setSpacing(1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lbl_Status = QtWidgets.QLabel(self.frame_3)
        self.lbl_Status.setObjectName("lbl_Status")
        self.gridLayout_9.addWidget(self.lbl_Status, 0, 0, 1, 1)
        self.lbl_Tip = QtWidgets.QLabel(self.frame_3)
        self.lbl_Tip.setObjectName("lbl_Tip")
        self.gridLayout_9.addWidget(self.lbl_Tip, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Serial Tool"))
        self.label_5.setText(_translate("Form", "Parity:"))
        self.cob_DataBits.setItemText(0, _translate("Form", "5"))
        self.cob_DataBits.setItemText(1, _translate("Form", "6"))
        self.cob_DataBits.setItemText(2, _translate("Form", "7"))
        self.cob_DataBits.setItemText(3, _translate("Form", "8"))
        self.cob_Baudrate.setItemText(0, _translate("Form", "2400"))
        self.cob_Baudrate.setItemText(1, _translate("Form", "4800"))
        self.cob_Baudrate.setItemText(2, _translate("Form", "9600"))
        self.cob_Baudrate.setItemText(3, _translate("Form", "19200"))
        self.cob_Baudrate.setItemText(4, _translate("Form", "38400"))
        self.cob_Baudrate.setItemText(5, _translate("Form", "56000"))
        self.cob_Baudrate.setItemText(6, _translate("Form", "57600"))
        self.cob_Baudrate.setItemText(7, _translate("Form", "115200"))
        self.cob_Baudrate.setItemText(8, _translate("Form", "230400"))
        self.cob_Baudrate.setItemText(9, _translate("Form", "460800"))
        self.cob_Baudrate.setItemText(10, _translate("Form", "921600"))
        self.cob_StopBits.setItemText(0, _translate("Form", "1"))
        self.cob_StopBits.setItemText(1, _translate("Form", "1.5"))
        self.cob_StopBits.setItemText(2, _translate("Form", "2"))
        self.cob_Parity.setItemText(0, _translate("Form", "None"))
        self.cob_Parity.setItemText(1, _translate("Form", "Odd"))
        self.cob_Parity.setItemText(2, _translate("Form", "Even"))
        self.cob_Parity.setItemText(3, _translate("Form", "Mark"))
        self.cob_Parity.setItemText(4, _translate("Form", "Space"))
        self.cob_FlowCtrl.setItemText(0, _translate("Form", "None"))
        self.cob_FlowCtrl.setItemText(1, _translate("Form", "Hardware"))
        self.cob_FlowCtrl.setItemText(2, _translate("Form", "Software"))
        self.cob_FlowCtrl.setItemText(3, _translate("Form", "Custom"))
        self.label_6.setText(_translate("Form", "FlowCtrl:"))
        self.label_3.setText(_translate("Form", "DataBits:"))
        self.label_4.setText(_translate("Form", "StopBits:"))
        self.label_2.setText(_translate("Form", "BaudRate:"))
        self.chk_HexSend.setText(_translate("Form", "Hex Send"))
        self.pb_Send.setText(_translate("Form", "Send(&S)"))
        self.label.setText(_translate("Form", "Port No:"))
        self.lbl_Com.setText(_translate("Form", "TextLabel"))
        self.pb_OpenOrClose.setText(_translate("Form", "打开(&O)"))
        self.chk_HexRecv.setText(_translate("Form", "Hex Recv"))
        self.pb_ClearRecv.setText(_translate("Form", "Clear Recv"))
        self.lbl_Status.setText(_translate("Form", "TextLabel"))
        self.lbl_Tip.setText(_translate("Form", "TextLabel"))

